### ISSUE TITLE
Color consistency

### ISSUE THREAD

**Issue by Aishnab** [Sosal-star/collaboratory#5]
A lack of visual coherence exists due to variations in color usage.

**Comment by Sosal-star** [comment]
> A lack of visual coherence exists due to variations in color usage.

I have fixed this issue✅

**Comment by Sakshyam-hub** [comment]
Hello Sosal, Only saying "I have fixed the issue" doesn't fix the issue, I have checked your branch you have neither solved the issue nor uploaded any kinds of files related to color consistency. Now, because of the lack of proper timing and lack of efficient work, I took the responsibility on my self and changed the color pallet using proper CSS and a good color pallet. This is the color pallet attached below: 
![image](https://github.com/Sosal-star/collaboratory/assets/119908783/8f068249-40df-4381-9c6f-b40b0059c3ae)
